-- ============================================================================
-- Database per "Il mio servizio"
-- Esegui tutto nel SQL Editor di Supabase (Project > SQL Editor > Run).
-- ============================================================================

-- Un profilo per utente: impostazioni generali (obiettivo annuale, nomi
-- personalizzati, tema, colori).
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  annual_goal_minutes integer not null default 36000,
  service_name text not null default 'Servizio di predicazione',
  work_name text not null default 'Lavori di manutenzione',
  study_name text not null default 'Studi biblici',
  theme text not null default 'light',
  service_color text not null default '#2563eb',
  work_color text not null default '#ff8a00',
  progress_color text not null default '#2563eb',
  button_color text not null default '#2563eb',
  -- NOVITA' (spec punto 18 "Impostazioni avanzate"): colore di icone, testi
  -- e sfondo, personalizzabili oltre a barra/pulsanti/servizio/lavoro.
  icon_color text not null default '#2563eb',
  text_color text not null default '#15243b',
  bg_color text not null default '#f7f9fc',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Se il database esisteva gia' da una versione precedente di questo
-- script, queste righe aggiungono le colonne mancanti senza errori.
alter table public.profiles add column if not exists icon_color text not null default '#2563eb';
alter table public.profiles add column if not exists text_color text not null default '#15243b';
alter table public.profiles add column if not exists bg_color text not null default '#f7f9fc';

-- Obiettivo di ogni singolo mese di un anno di servizio.
-- IMPORTANTE: "service_year" e' l'anno di INIZIO dell'anno di servizio, che
-- va da settembre a agosto (es. l'anno di servizio 2026 copre settembre
-- 2026 - agosto 2027). Un mese come "gennaio 2027" appartiene percio'
-- all'anno di servizio 2026, NON al 2027: e' l'errore che il codice
-- dell'app commetteva prima di essere corretto (vedi js/selectors.js,
-- funzione serviceYearForKey, lato applicazione).
create table if not exists public.month_goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  service_year integer not null,
  month integer not null check (month between 1 and 12),
  goal_minutes integer not null default 3300,
  unique(user_id, service_year, month)
);

-- Ogni singolo inserimento di ore (servizio o lavoro) in un giorno preciso.
create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  entry_type text not null check (entry_type in ('service', 'work')),
  minutes integer not null check (minutes >= 0 and minutes <= 1440), -- max 24h per voce
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Indice usato per velocizzare le query per utente + intervallo di date.
create index if not exists time_entries_user_date_idx on public.time_entries(user_id, entry_date);

-- Conteggio studi biblici per mese (stessa convenzione di service_year di month_goals).
create table if not exists public.month_stats (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  service_year integer not null,
  month integer not null check (month between 1 and 12),
  studies integer not null default 0 check (studies >= 0),
  unique(user_id, service_year, month)
);

-- --- Sicurezza: Row Level Security --------------------------------------
-- Ogni utente puo' leggere/modificare soltanto le proprie righe.
alter table public.profiles enable row level security;
alter table public.month_goals enable row level security;
alter table public.time_entries enable row level security;
alter table public.month_stats enable row level security;

create policy "profiles own" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "goals own" on public.month_goals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "entries own" on public.time_entries for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "stats own" on public.month_stats for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Crea automaticamente un profilo vuoto ogni volta che si registra un nuovo utente.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Realtime (utile per sincronizzazione tra dispositivi aperti contemporaneamente).
alter publication supabase_realtime add table public.time_entries;
alter publication supabase_realtime add table public.month_goals;
alter publication supabase_realtime add table public.month_stats;
